<?php
$pmpFieldValuesLost = array ( 
/*Label & Values for Search Filters */
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_AGE_GROUP') . '_' . constant('LOST_METHODTYPE_PETPOINT')	=> 'Age Group',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('PETPOINT_AGE_GROUP') . '_' . constant('LOST_METHODTYPE_PETPOINT')	=> array('All' => 'All', 'OverYear' => 'Over 1 Year Old', 'UnderYear' => 'Under 1 Year Old'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_ID_SPECIES') . '_' . constant('LOST_METHODTYPE_PETPOINT')	=> 'Species',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('PETPOINT_ID_SPECIES') . '_' . constant('LOST_METHODTYPE_PETPOINT')	=> array('0' => 'All', '1' => 'Dog', '2' => 'Cat', '3' => 'Other'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_ORDERBY') . '_' . constant('LOST_METHODTYPE_PETPOINT')		=> 'Order by',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('PETPOINT_ORDERBY') . '_' . constant('LOST_METHODTYPE_PETPOINT')		=> array( 'Breed' => 'Breed', 'DateFirst' => 'Date Lost, Ascending', 'DateLast' => 'Date Lost, Descending', 'ID' => 'ID', 'Name' => 'Name', 'Sex' => 'Sex'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_SEX') . '_' . constant('LOST_METHODTYPE_PETPOINT')			=> 'Sex',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('PETPOINT_SEX') . '_' . constant('LOST_METHODTYPE_PETPOINT')			=> array('A' => 'All', 'M' => 'Male', 'F' => 'Female'),

/*Labels for Search Sort Fields */
constant('LABEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_BREED') . '_' . constant('LOST_METHODTYPE_PETPOINT')			=> 'Breed',
constant('LABEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_DATE_FIRST') . '_' . constant('LOST_METHODTYPE_PETPOINT')	=> 'Date Lost, Ascending',
constant('LABEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_DATE_LAST') . '_' . constant('LOST_METHODTYPE_PETPOINT')		=> 'Date Lost, Descending',
constant('LABEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_ID') . '_' . constant('LOST_METHODTYPE_PETPOINT')			=> 'ID',
constant('LABEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_NAME') . '_' . constant('LOST_METHODTYPE_PETPOINT')			=> 'Name',
constant('LABEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_SEX') . '_' . constant('LOST_METHODTYPE_PETPOINT')			=> 'Sex',

/* Labels for Search Results */
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_AGE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Age',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_ALTERED_SPAY_NEUTERED') . '_' . constant('LOST_METHODTYPE_PETPOINT')	=> 'Spayed/Neutered',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_BREED_PRIMARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Primary Breed', 
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_BREED_SECONDARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Secondary Breed', 
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_COLOR_PRIMARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Primary Color',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_COLOR_SECONDARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Secondary Color',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_DATE_LOST') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Date Lost',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_ID') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Animal Number',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_LOST_ADDRESS') . '_' . constant('LOST_METHODTYPE_PETPOINT') 	=> 'Address Lost',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_LOST_CITY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 		=> 'City Lost',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_LOST_STATE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 		=> 'State Lost',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_NAME') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Name',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_PHOTO') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Photo',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_SEX') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Sex',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_SPECIES') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Species',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_TYPE') . '_' . constant('LOST_METHODTYPE_PETPOINT')						=> 'Type',

/*Labels for Animal Details */
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_AGE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Age', 
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_BREED_PRIMARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Primary Breed', 
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_BREED_SECONDARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Secondary Breed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COAT') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Coat',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_COLOR') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Color Color',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_2_COLOR') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Color 2 Color',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_TYPE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Color Type',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_2_TYPE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Color 2 Type',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLOR_EYE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Eyes',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLOR_PRIMARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Primary Color',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLOR_SECONDARY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Secondary Color',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_DATE_LOST') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Date Lost',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_DECLAWED') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Declawed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_DESCRIPTION') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Description',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_EAR') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Ears',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_ID') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Animal Number',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_ID_COMPANY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Company ID',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_JURISDICTION') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Jurisdiction Lost',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION_LOST') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Location Lost',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION_LOST_CITY') . '_' . constant('LOST_METHODTYPE_PETPOINT') 		=> 'City Lost',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION_LOST_STATE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 		=> 'State Lost',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_MARKS') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Marks',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_MARKS_PATTERN') . '_' . constant('LOST_METHODTYPE_PETPOINT') 			=> 'Color Pattern',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_NAME_ANIMAL') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Animal Name',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_PHOTO') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Photo',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SEX') . '_' . constant('LOST_METHODTYPE_PETPOINT') 						=> 'Sex',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SIZE') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Size',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SPECIES') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Species',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_TAIL') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Tail',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_WEIGHT') . '_' . constant('LOST_METHODTYPE_PETPOINT') 					=> 'Body Weight',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_WEIGHT_UOM') . '_' . constant('LOST_METHODTYPE_PETPOINT') 				=> 'Body Weight Unit'
);
?>