<?php
$pmpFieldLevelsFound = array ( 
/*License Levels for Search Options */
constant('LEVEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_AGE_GROUP') . '_' . constant('FOUND_METHODTYPE_PETPOINT')	=> 2,
constant('LEVEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_ID_SPECIES') . '_' . constant('FOUND_METHODTYPE_PETPOINT')	=> 2,
constant('LEVEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_ORDERBY') . '_' . constant('FOUND_METHODTYPE_PETPOINT')		=> 2,
constant('LEVEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_TYPE_SEARCH') . '_' . constant('FOUND_METHODTYPE_PETPOINT')=> 2, 
constant('LEVEL_PREFIX_SEARCH_FILTER') . constant('PETPOINT_SEX') . '_' . constant('FOUND_METHODTYPE_PETPOINT')			=> 2,

/*License Levels for Search Sort Fields */
constant('LEVEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_BREED') . '_' . constant('FOUND_METHODTYPE_PETPOINT')		=> 2,
constant('LEVEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_DATE_FIRST') . '_' . constant('FOUND_METHODTYPE_PETPOINT')	=> 2,
constant('LEVEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_DATE_LAST') . '_' . constant('FOUND_METHODTYPE_PETPOINT')	=> 3,
constant('LEVEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_ID') . '_' . constant('FOUND_METHODTYPE_PETPOINT')			=> 2,
constant('LEVEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_NAME') . '_' . constant('FOUND_METHODTYPE_PETPOINT')			=> 2,
constant('LEVEL_PREFIX_SEARCH_SORT') .  constant('PETPOINT_SEX') . '_' . constant('FOUND_METHODTYPE_PETPOINT')			=> 2,

/* License Levels for Search Results */
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_AGE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_ALTERED_SPAY_NEUTERED') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_BREED_PRIMARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2, 
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_BREED_SECONDARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 		=> 2, 
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_COLOR_PRIMARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_COLOR_SECONDARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 		=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_DATE_FOUND') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_ID') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 						=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_JURISDICTION') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_FOUND') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_FOUND_ADDRESS') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_FOUND_CITY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_LOCATION_FOUND_STATE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_NAME') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_PHOTO') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_SEX') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_SPECIES') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_STAGE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_SEARCH_RESULT') . constant('PETPOINT_TYPE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,

/* License Levels for Animal Details */
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_AGE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2, 
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_BREED_PRIMARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2, 
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_BREED_SECONDARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 		=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLOR_EYE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLOR_PRIMARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLOR_SECONDARY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 		=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COAT') . '_' . constant('FOUND_METHODTYPE_PETPOINT')					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_COLOR') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_2_COLOR') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_TYPE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_COLLAR_2_TYPE'). '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_DATE_FOUND') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_DECLAWED') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_DESCRIPTION') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_EAR') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_ID') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 						=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_ID_COMPANY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_JURISDICTION') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION_FOUND') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION_FOUND_CITY') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_LOCATION_FOUND_STATE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_MARKS') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_MARKS_PATTERN') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_NAME_ANIMAL') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_PHOTO') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SEX') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SITE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SIZE') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_SPECIES') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_TAIL') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_TYPE_FOUND') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_WEIGHT') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 					=> 2,
constant('LEVEL_PREFIX_ANIMAL_DETAIL') . constant('PETPOINT_WEIGHT_UOM') . '_' . constant('FOUND_METHODTYPE_PETPOINT') 				=> 2,

/* Include Keys for Additional Premium Features */
'level_buttons_conversion_' . constant('FOUND_METHODTYPE_PETPOINT') 	=> 2,
'level_buttons_other_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
'level_LEVEL_search_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2,
'level_social_share_' . constant('FOUND_METHODTYPE_PETPOINT') 			=> 2
);
?>