<?php
$pmpOptionLevelsContact = array ( 
'level_social_share' => 2,
'level_phone_adopt' => 3,
'level_email_adopt' => 3,
'level_link_adopt' => 3,
'level_vanity_link_adopt' => 2,
'level_foster_phone_adopt' => 3,
'level_foster_email_adopt' => 3,
'level_foster_link_adopt' => 3,
'level_foster_vanity_link_adopt' => 2,
'level_donate_link_adopt' => 3,
'level_vanity_link_donate' => 2,
'level_vanity_link_volunteer' => 2,
'level_hours_link_adopt' => 3,
'level_phone_found' => 2,
'enable_phone_found_af' => 1,
'enable_phone_found_pp' => 1,
'enable_phone_found_rg' => 0,
'level_email_found' => 2,
'enable_email_found_af' => 1,
'enable_email_found_pp' => 1,
'enable_email_found_rg' => 0,
'level_phone_lost' => 2,
'enable_phone_lost_af' => 1,
'enable_phone_lost_pp' => 1,
'enable_phone_lost_rg' => 0,
'level_email_lost' => 2,
'enable_email_lost_af' => 1,
'enable_email_lost_pp' => 1,
'enable_email_lost_rg' => 0,
'level_sponsor_link' => 1,
'level_sponsor_image' => 1,
'level_email_website' => 3
)
?>