<?php
	$ValuesPMPLicenseTypeID = (int) get_option('PMP_License_Type_ID');  
	//echo 'Adopt Field Values License Type Before Checking = ' . $ValuesPMPLicenseTypeID . '<br>';

	if ( $ValuesPMPLicenseTypeID == 0 ) {
		$ValuesPMPLicenseTypeID = constant('FREE_LEVEL');
	}

	//echo 'Adopt Field Values License Type = ' . $ValuesPMPLicenseTypeID . '<br>';

$pmpFieldValuesAdopt = array ( 
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_DECLAWED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Declawed',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_DECLAWED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_AGE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Age Group',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_AGE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> array('All' => 'All', 'Baby' => 'Baby', 'Young' => 'Young', 'Adult' => 'Adult', 'Senior' => 'Senior'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_FOSTER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Foster Needed',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_FOSTER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_OK_CATS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Good with Cats',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_OK_CATS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_OK_DOGS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Good with Dogs',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_OK_DOGS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_OK_KIDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Good with Kids',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_OK_KIDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SEARCH_STRING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Text Search',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SEARCH_STRING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> '',
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SEX') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Sex',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SEX') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> array('All' => 'All', 'Male' => 'Male', 'Female' => 'Female'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIAL_DIET') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Special Diet',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIAL_DIET') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIAL_NEEDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Special Needs',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIAL_NEEDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Species',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('All' => 'All', 'cat' => 'Cat', 'dog' => 'Dog'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_YARD') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Yard Required',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_YARD') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('All' => 'Either', 'Yes' => 'Yes', 'No' => 'No'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_ORDERBY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Sort by',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_ORDERBY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> array('animalbirthdate' => 'Birth Date', 'animalid' => 'Animal ID', 'animalsex' => 'Sex', 'animalname' => 'Name'),
constant('LABEL_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SORTORDER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Sort Order',
constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SORTORDER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> array('asc' => 'Ascending', 'desc' => 'Descending'),

/*Labels for Search Sort Fields */
constant('LABEL_PREFIX_SEARCH_SORT') . constant('RESCUEGROUPS_DATE_BIRTH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Birth Date',
constant('LABEL_PREFIX_SEARCH_SORT') . constant('RESCUEGROUPS_ID') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Animal ID',
constant('LABEL_PREFIX_SEARCH_SORT') . constant('RESCUEGROUPS_SEX') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Sex',
constant('LABEL_PREFIX_SEARCH_SORT') . constant('RESCUEGROUPS_NAME') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Name',

/*Labels for Search Sort Order Values */
constant('LABEL_PREFIX_SEARCH_ORDER') . constant('RESCUEGROUPS_SORTORDER_ASCENDING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Ascending',
constant('LABEL_PREFIX_SEARCH_ORDER') . constant('RESCUEGROUPS_SORTORDER_DESCENDING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Descending',

/* Labels for Search Results */
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ACTIVITY_LEVEL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Activity Level',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ADOPTION_FEE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Adoption Fee',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ADOPTION_PENDING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Adoption Pending',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_AFFECTIONATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Affectionate',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_AGE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'General Age',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ALLERGIES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Has Allergies',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ALTERED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Altered',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_APARTMENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Apartment',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_BREED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Breed',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_BREED_MIXED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Mixed Breed',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_BREED_PRIMARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Primary Breed',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_BREED_SECONDARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Secondary Breed',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_CAR') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Good in Car',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_COAT_LENGTH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Coat Length',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_COLOR_DETAILS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Color Details',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_COLOR_EYE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Eye Color',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_COLOR_PRIMARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Color',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_COMPANION_ANIMAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Needs Companion Animal',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_COURTESY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Courtesy',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_CRATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Crate Trained',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DATE_AVAILABLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Available Date',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DATE_BIRTH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Birth Date',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DATE_BIRTH_EXACT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Birth Date Exact',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DATE_FOUND') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Found Date',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DATE_UPDATED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Update Date',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DECLAWED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Declawed',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DESCRIPTION') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Description',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DESCRIPTION_SUMMARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Summary',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_DROOLS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Drools',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_EAGER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Eager to Please',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_EAR') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Ear Type',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ENERGY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Energy Level',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ESCAPES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Escapes',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_EVEN_TEMPERED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Even Tempered',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_EXERCISE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Needs Exercise',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_FENCE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Fence Required',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_FETCHES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Fetches',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_FOSTER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Needs Foster',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_FOUND') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Found',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_FOUND_ZIP') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Found in Postal Code',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_GENTLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Gentle',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_GOOFY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Goofy',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_GROOMING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Grooming Needs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_HEARING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Hearing Impaired',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_HOUSETRAINED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Housetrained',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_HOUSETRAINED_INFO') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Housetraining Reason',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_HYPOALLERGENIC') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Hypoallergenic',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_ID') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'ID',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_INDEPENDENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Independent',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_INDOOR_OUTDOOR') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Indoor/Outdoor',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_INTELLIGENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Intelligent',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LAP') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Lap',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LEASH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Leash Trained',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Location',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_ADDRESS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Address',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_CITY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'City',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_COUNTRY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Country',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_PHONE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Phone',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_STATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'State',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_URL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Location Link',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_LOCATION_ZIP') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Zip',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_MARKS_DISTINGUISHING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Distinguishing Marks',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_MARKS_PATTERN') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Pattern',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_MEDIA') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Media',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_MEDICAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'On-Going Medical Needs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_MICROCHIPPED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Microchipped',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_NAME') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Name',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_NEW_PEOPLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'New People',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OBEDIENCE_TRAINING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Obedience Trained',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OBEDIENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Obedient',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_ADULTS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'OK with Adults',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_CATS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Cats',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_COLD') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'No Cold',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_DOGS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Dogs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_DOGS_FEMALE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Female Dogs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_DOGS_LARGE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Large Dogs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_DOGS_MALE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Male Dogs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_DOGS_SMALL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Small Dogs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_FARM') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Farm Animals',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_HEAT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'No Heat',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_KIDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Kids',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_KIDS_OLDER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Older Kids Only',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OK_SENIORS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'OK for Seniors',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_OWNER_EXPERIENCE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Owner Experience',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_PHOTOS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Photos',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_PHOTO_THUMBNAIL_URL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Thumbnail Link',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_PLAYFUL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Playful',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_PREDATORY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Predatory',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_PROFILE_URL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Profile Link',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_PROTECTIVE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Protective',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SEARCH_STRING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Text Search',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SEX') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Sex',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SHEDDING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Shedding',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SIZE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Weight',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SIZE_POTENTIAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Weight Potential',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SIZE_POTENTIAL_GENERAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Size Potential',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SIZE_UOM') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Weight Unit of Measure',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SKITTISH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Skittish',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPECIAL_DIET') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Special Diet',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPECIAL_NEEDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Special Needs',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPECIAL_NEEDS_INFO') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Special Need Reason',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPECIES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Species',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPONSORABLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Sponsorable',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPONSORS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Sponsors',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPONSORSHIP_INFO') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Sponsorship Details',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SPONSORSHIP_MIN') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Sponsorship Minimum',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_SWIMS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Swims',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_STATUS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Status',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_TAIL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Tail Type',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_TIMID') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Timid',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_TOYS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Plays with Toys',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_UPTODATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Uptodate',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_VIDEOS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Videos',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_VISION') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Sight Impaired',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_VOCAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Vocal',
constant('LABEL_PREFIX_SEARCH_RESULT') . constant('RESCUEGROUPS_YARD') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Yard Required',

/* Labels for Animal Details */
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ACTIVITY_LEVEL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Activity Level',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ADOPTION_FEE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Adoption Fee',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ADOPTION_PENDING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Adoption Pending',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_AFFECTIONATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Affectionate',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_AGE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'General Age',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ALLERGIES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Has Allergies',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ALTERED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Altered',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_APARTMENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Apartment',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_BREED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Breed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_BREED_MIXED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Mixed Breed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_BREED_PRIMARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Primary Breed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_BREED_SECONDARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Secondary Breed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_CAR') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Good in Car',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_COAT_LENGTH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Coat Length',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_COLOR_DETAILS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Color Details',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_COLOR_EYE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Eye Color',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_COLOR_PRIMARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Color',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_COMPANION_ANIMAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Needs Companion Animal',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_COURTESY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Courtesy',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_CRATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Crate Trained',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DATE_AVAILABLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Available Date',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DATE_BIRTH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Birth Date',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DATE_BIRTH_EXACT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Birth Date Exact',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DATE_FOUND') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Found Date',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DATE_UPDATED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Update Date',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DECLAWED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Declawed',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DESCRIPTION') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Description',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DESCRIPTION_SUMMARY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Summary',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_DROOLS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Drools',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_EAGER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Eager to Please',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_EAR') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Ear Type',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ENERGY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Energy Level',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ESCAPES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Escapes',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_EVEN_TEMPERED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Even Tempered',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_EXERCISE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Needs Exercise',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_FENCE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Fence Required',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_FETCHES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Fetches',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_FOSTER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Needs Foster',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_FOUND') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Found',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_FOUND_ZIP') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Found in Postal Code',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_GENTLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Gentle',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_GOOFY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Goofy',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_GROOMING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Grooming Needs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_HEARING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Hearing Impaired',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_HOUSETRAINED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Housetrained',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_HOUSETRAINED_INFO') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Housetraining Reason',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_HYPOALLERGENIC') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Hypoallergenic',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_ID') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'ID',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_INDEPENDENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Independent',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_INDOOR_OUTDOOR') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Indoor/Outdoor',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_INTELLIGENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Intelligent',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LAP') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Lap',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LEASH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Leash Trained',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Location',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_ADDRESS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Address',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_CITY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'City',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_COUNTRY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Country',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_PHONE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Phone',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_STATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'State',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_URL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Location Link',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_LOCATION_ZIP') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Zip',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_MARKS_DISTINGUISHING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Distinguishing Marks',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_MARKS_PATTERN') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Pattern',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_MEDIA') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Media',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_MEDICAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'On-Going Medical Needs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_MICROCHIPPED') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Microchipped',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_NAME') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Name',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_NEW_PEOPLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'New People',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OBEDIENCE_TRAINING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Obedience Trained',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OBEDIENT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Obedient',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_ADULTS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'OK with Adults',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_CATS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Cats',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_COLD') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'No Cold',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_DOGS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Dogs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_DOGS_FEMALE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Female Dogs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_DOGS_LARGE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Large Dogs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_DOGS_MALE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Male Dogs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_DOGS_SMALL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'No Small Dogs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_FARM') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Farm Animals',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_HEAT') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'No Heat',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_KIDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'OK with Kids',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_KIDS_OLDER') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Older Kids Only',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OK_SENIORS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'OK for Seniors',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_OWNER_EXPERIENCE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Owner Experience',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_PHOTOS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Photos',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_PHOTO_THUMBNAIL_URL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Thumbnail Link',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_PLAYFUL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Playful',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_PREDATORY') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Predatory',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_PROFILE_URL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Profile Link',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_PROTECTIVE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Protective',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SEARCH_STRING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Text Search',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SEX') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')					=> 'Sex',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SHEDDING') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Shedding',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SIZE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Weight',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SIZE_POTENTIAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Weight Potential',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SIZE_POTENTIAL_GENERAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')	=> 'Size Potential',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SIZE_UOM') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Weight Unit of Measure',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SKITTISH') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Skittish',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPECIAL_DIET') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Special Diet',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPECIAL_NEEDS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Special Needs',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPECIAL_NEEDS_INFO') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Special Need Reason',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPECIES') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Species',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPONSORABLE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Sponsorable',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPONSORS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Sponsors',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPONSORSHIP_INFO') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Sponsorship Details',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SPONSORSHIP_MIN') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')		=> 'Sponsorship Minimum',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_SWIMS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Swims',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_STATUS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Status',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_TAIL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Tail Type',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_TIMID') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Timid',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_TOYS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Plays with Toys',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_UPTODATE') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')			=> 'Uptodate',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_VIDEOS') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Videos',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_VISION') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Sight Impaired',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_VOCAL') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Vocal',
constant('LABEL_PREFIX_ANIMAL_DETAIL') . constant('RESCUEGROUPS_YARD') . '_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')				=> 'Yard Required'
);

	/* Remove Premium Species Filter as Required */
	if ( $ValuesPMPLicenseTypeID == constant('FREE_LEVEL') ) {
		/* Get Free Species Values */
		$speciesFree = [];
		$speciesFree = explode(",", constant('FREE_SPECIES'));
		//echo '<pre>FREE SPECIES<br>'; print_r($speciesFree); echo '</pre>';
		
//		$speciesFilter = $pmpFieldValuesAdopt['value_filter_animalspecies_' . constant('ADOPT_METHODTYPE_RESCUEGROUPS')];
//		foreach ( $speciesFilter as $key => $value ) {
//			if (in_array(strtolower($value), $speciesFree)) {
//				$freeFilter[$key] = $value;
//			}
//		}

		if ( is_array($speciesFree) ) {
//		if ( is_array($freeFilter) ) {
			$pmpFieldValuesAdopt[constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIES') . constant('ADOPT_METHODTYPE_RESCUEGROUPS')] = $speciesFree;
//			$pmpFieldValuesAdopt[constant('VALUE_PREFIX_SEARCH_FILTER') . constant('RESCUEGROUPS_SPECIES') . constant('ADOPT_METHODTYPE_RESCUEGROUPS')] = $freeFilter;
		}
	}
?>